# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_with_friends', '0002_auto_20170427_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsideRouteTable',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('outside_route_id', models.TextField(blank=True, null=True)),
                ('full_day', models.NullBooleanField()),
                ('regular', models.NullBooleanField()),
                ('origin_city', models.TextField(blank=True, null=True)),
                ('origin_state', models.TextField(blank=True, null=True)),
                ('target_direction', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('event_type', models.TextField(blank=True, null=True)),
                ('event_ids', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outside_route_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OutsideTripTable',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('outside_trip_id', models.TextField(blank=True, null=True)),
                ('outside_route_ids', models.TextField(blank=True, null=True)),
                ('event_id_lst', models.TextField(blank=True, null=True)),
                ('origin_city', models.TextField(blank=True, null=True)),
                ('origin_state', models.TextField(blank=True, null=True)),
                ('target_direction', models.TextField(blank=True, null=True)),
                ('n_days', models.FloatField(blank=True, null=True)),
                ('regular', models.NullBooleanField()),
                ('full_day', models.NullBooleanField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outside_trip_table',
                'managed': False,
            },
        ),
    ]
